version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: localhost:5000/frontend
    ports:
      - 9000:3000
    environment:
      - SERVICE_API1_ENDPOINT=http://localhost:9010/api
      - PORT=3000
    networks:
      - microservice-network

  backend1:
    build:
      context: .
      dockerfile: backend1/Dockerfile
    image: localhost:5000/backend1
    ports:
      - 9010:3010
    environment:
      - SERVICE_API2_ENDPOINT=http://backend2:3020/api
      - PORT=3010
    networks:
      - microservice-network

  backend2:
    build:
      context: .
      dockerfile: backend2/Dockerfile
    image: localhost:5000/backend2
    ports:
      - 3020
    depends_on:
      - backend1
    environment:
      - PORT=3020
    networks:
      - microservice-network

networks:
  microservice-network:
